//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_landmarks p_landmarks;
        
        public static SteamVR_Input_ActionSet_landmarks landmarks
        {
            get
            {
                return SteamVR_Actions.p_landmarks.GetCopy<SteamVR_Input_ActionSet_landmarks>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_landmarks = ((SteamVR_Input_ActionSet_landmarks)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_landmarks>("/actions/landmarks")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.landmarks};
        }
    }
}
