//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_vrtk : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TouchpadButton
        {
            get
            {
                return SteamVR_Actions.vrtk_TouchpadButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.vrtk_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripButton
        {
            get
            {
                return SteamVR_Actions.vrtk_GripButton;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.vrtk_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.vrtk_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.vrtk_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerSqueeze
        {
            get
            {
                return SteamVR_Actions.vrtk_TriggerSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.vrtk_TouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadPosition
        {
            get
            {
                return SteamVR_Actions.vrtk_TouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonStartMenu
        {
            get
            {
                return SteamVR_Actions.vrtk_ButtonStartMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.vrtk_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTwoTouch
        {
            get
            {
                return SteamVR_Actions.vrtk_TouchpadTwoTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadTwoPosition
        {
            get
            {
                return SteamVR_Actions.vrtk_TouchpadTwoPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTwoButton
        {
            get
            {
                return SteamVR_Actions.vrtk_TouchpadTwoButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripTouch
        {
            get
            {
                return SteamVR_Actions.vrtk_GripTouch;
            }
        }
        
        public virtual SteamVR_Action_Single GripSqueeze
        {
            get
            {
                return SteamVR_Actions.vrtk_GripSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonOneTouch
        {
            get
            {
                return SteamVR_Actions.vrtk_ButtonOneTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonOneClick
        {
            get
            {
                return SteamVR_Actions.vrtk_ButtonOneClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonTwoTouch
        {
            get
            {
                return SteamVR_Actions.vrtk_ButtonTwoTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean ButtonTwoClick
        {
            get
            {
                return SteamVR_Actions.vrtk_ButtonTwoClick;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vrtk_Haptic;
            }
        }
    }
}
