//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_landmarks : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.landmarks_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.landmarks_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.landmarks_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.landmarks_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripButton
        {
            get
            {
                return SteamVR_Actions.landmarks_GripButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadButton
        {
            get
            {
                return SteamVR_Actions.landmarks_TouchpadButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpperButton
        {
            get
            {
                return SteamVR_Actions.landmarks_UpperButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean LowerButton
        {
            get
            {
                return SteamVR_Actions.landmarks_LowerButton;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerSqueeze
        {
            get
            {
                return SteamVR_Actions.landmarks_TriggerSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Single GripSqueeze
        {
            get
            {
                return SteamVR_Actions.landmarks_GripSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.landmarks_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripTouch
        {
            get
            {
                return SteamVR_Actions.landmarks_GripTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.landmarks_TouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpperTouch
        {
            get
            {
                return SteamVR_Actions.landmarks_UpperTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean LowerTouch
        {
            get
            {
                return SteamVR_Actions.landmarks_LowerTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadPosition
        {
            get
            {
                return SteamVR_Actions.landmarks_TouchpadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.landmarks_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.landmarks_Haptic;
            }
        }
    }
}
